## Insigts of datasets

In [4]:
import pandas as pd
import requests

### National electricity consumption

National electricity consumption, including consumption by storage pumps, is an important indicator of the electricity supply. The trend is initially presented based on data reported to Swissgrid by distribution system operators. This data may be incomplete or incorrect and is subsequently corrected. Final consumption indicates how much electricity is consumed by households, commerce, agriculture, services, industry, and transportation. When it comes to the Swiss public’s energy-saving efforts, it is the key metric. The trend is initially displayed based on data reported to Swissgrid by distribution network operators. This data may be incomplete or incorrect and is subject to correction.\nIn this specific dataset, updated values are appended to the existing data rather than overwriting older entries. The most recent entry for each date corresponds to the most current and valid value. The purpose of this structure is to provide a transparent history of data changes.

In [31]:
response = requests.get("https://energiedashboard.ch/api/v1/datasets/stromverbrauch-swissgrid-lv-und-endv/data?offset=0")

data = response.json()
df = pd.DataFrame(data['data'])

In [41]:
df[df['energietraeger'] == 'Kernkraft']

         datum energietraeger  produktion_gwh
1   2025-07-01      Kernkraft            34.1
2   2025-09-12      Kernkraft            37.5
4   2026-06-01      Kernkraft            18.7
5   2026-06-04      Kernkraft            20.8
6   2026-06-03      Kernkraft            17.1
20  2025-07-02      Kernkraft            30.7
23  2025-07-03      Kernkraft            28.2
27  2025-07-04      Kernkraft            28.4
29  2025-07-05      Kernkraft            28.4
33  2025-07-06      Kernkraft            28.6
36  2025-07-07      Kernkraft            29.7
40  2025-07-08      Kernkraft            37.8
44  2025-07-09      Kernkraft            45.8
48  2025-07-10      Kernkraft            45.8
51  2025-07-11      Kernkraft            44.9
54  2025-07-12      Kernkraft            43.4
57  2025-07-13      Kernkraft            43.4
61  2025-07-14      Kernkraft            43.8
63  2025-07-15      Kernkraft            44.1
65  2025-07-16      Kernkraft            44.2
68  2025-07-17      Kernkraft            44.3
71  2025-07-18      Kernkraft            32.6
74  2025-07-19      Kernkraft            23.2
78  2025-07-20      Kernkraft            23.3
82  2025-07-21      Kernkraft            23.3
85  2025-07-22      Kernkraft            17.3
88  2025-07-23      Kernkraft            27.6
91  2025-07-24      Kernkraft            39.1
94  2025-07-25      Kernkraft            42.1
98  2025-07-26      Kernkraft            44.1

In [30]:
df.duplicated().any()

np.False_

### Electricity Generation

In [ ]:
response = requests.get("https://energiedashboard.ch/api/v1/datasets/stromproduktion-swissgrid/data?offset=0")

data = response.json()
df = pd.DataFrame(data['data'])

In [39]:

df[df['datum'] > '2025-01-01']

         datum energietraeger  produktion_gwh
0   2026-06-07     Thermische             7.3
1   2025-07-01      Kernkraft            34.1
2   2025-09-12      Kernkraft            37.5
3   2026-03-01  Speicherkraft            27.5
4   2026-06-01      Kernkraft            18.7
..         ...            ...             ...
95  2025-07-25   Photovoltaik            29.0
96  2025-07-25     Thermische             9.9
97  2025-07-25           Wind             0.1
98  2025-07-26      Kernkraft            44.1
99  2025-07-26     Thermische             9.9

[100 rows x 3 columns]

In [31]:
df.duplicated().any()

np.False_

### Meteo

In [6]:
response = requests.get("https://data.geo.admin.ch/api/stac/v1/collections/ch.meteoschweiz.ogd-smn/items")
data = response.json()

df = pd.DataFrame(data['features'])
df.head()

,id,collection,type,stac_version,geometry,bbox,properties,stac_extensions,links,assets
0,abo,ch.meteoschweiz.ogd-smn,Feature,1.0.0,"{'type': 'Point', 'coordinates': [7.560703, 46...","[7.560703, 46.491703, 7.560703, 46.491703]","{'datetime': '2026-07-02T04:00:36.285372Z', 't...",[https://stac-extensions.github.io/timestamps/...,"[{'rel': 'self', 'href': 'https://data.geo.adm...",{'ogd-smn_abo_d_historical.csv': {'type': 'tex...
1,aeg,ch.meteoschweiz.ogd-smn,Feature,1.0.0,"{'type': 'Point', 'coordinates': [8.608206, 47...","[8.608206, 47.133636, 8.608206, 47.133636]","{'datetime': '2026-07-02T04:00:36.285532Z', 't...",[https://stac-extensions.github.io/timestamps/...,"[{'rel': 'self', 'href': 'https://data.geo.adm...",{'ogd-smn_aeg_d_historical.csv': {'type': 'tex...
2,aig,ch.meteoschweiz.ogd-smn,Feature,1.0.0,"{'type': 'Point', 'coordinates': [6.924472, 46...","[6.924472, 46.326647, 6.924472, 46.326647]","{'datetime': '2026-07-02T04:00:36.285661Z', 't...",[https://stac-extensions.github.io/timestamps/...,"[{'rel': 'self', 'href': 'https://data.geo.adm...",{'ogd-smn_aig_d_historical.csv': {'type': 'tex...
3,alt,ch.meteoschweiz.ogd-smn,Feature,1.0.0,"{'type': 'Point', 'coordinates': [8.621894, 46...","[8.621894, 46.887069, 8.621894, 46.887069]","{'datetime': '2026-07-02T04:00:36.285822Z', 't...",[https://stac-extensions.github.io/timestamps/...,"[{'rel': 'self', 'href': 'https://data.geo.adm...",{'ogd-smn_alt_d_historical.csv': {'type': 'tex...
4,and,ch.meteoschweiz.ogd-smn,Feature,1.0.0,"{'type': 'Point', 'coordinates': [9.431981, 46...","[9.431981, 46.610139, 9.431981, 46.610139]","{'datetime': '2026-07-02T04:00:36.285929Z', 't...",[https://stac-extensions.github.io/timestamps/...,"[{'rel': 'self', 'href': 'https://data.geo.adm...",{'ogd-smn_and_d_historical.csv': {'type': 'tex...

In [11]:
assets = [item['assets'] for item in data['features']]
[(filename, metadata['href']) for asset in assets for (filename, metadata) in asset.items()]

[('ogd-smn_abo_d_historical.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_d_historical.csv'),
 ('ogd-smn_abo_d_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_d_recent.csv'),
 ('ogd-smn_abo_h_historical_1980-1989.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_h_historical_1980-1989.csv'),
 ('ogd-smn_abo_h_historical_1990-1999.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_h_historical_1990-1999.csv'),
 ('ogd-smn_abo_h_historical_2000-2009.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_h_historical_2000-2009.csv'),
 ('ogd-smn_abo_h_historical_2010-2019.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_h_historical_2010-2019.csv'),
 ('ogd-smn_abo_h_historical_2020-2029.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_h_historical_2020-2029.csv'),
 ('ogd-smn_abo_h_now.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_h_now.csv'),
 ('ogd-smn_abo_h_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_h_recent.csv'),
 ('ogd-smn_abo_m.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_m.csv'),
 ('ogd-smn_abo_t_historical_2000-2009.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_t_historical_2000-2009.csv'),
 ('ogd-smn_abo_t_historical_2010-2019.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_t_historical_2010-2019.csv'),
 ('ogd-smn_abo_t_historical_2020-2029.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_t_historical_2020-2029.csv'),
 ('ogd-smn_abo_t_now.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_t_now.csv'),
 ('ogd-smn_abo_t_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_t_recent.csv'),
 ('ogd-smn_abo_y.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_y.csv'),
 ('ogd-smn_aeg_d_historical.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_d_historical.csv'),
 ('ogd-smn_aeg_d_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_d_recent.csv'),
 ('ogd-smn_aeg_h_historical_1990-1999.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_h_historical_1990-1999.csv'),
 ('ogd-smn_aeg_h_historical_2000-2009.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_h_historical_2000-2009.csv'),
 ('ogd-smn_aeg_h_historical_2010-2019.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_h_historical_2010-2019.csv'),
 ('ogd-smn_aeg_h_historical_2020-2029.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_h_historical_2020-2029.csv'),
 ('ogd-smn_aeg_h_now.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_h_now.csv'),
 ('ogd-smn_aeg_h_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_h_recent.csv'),
 ('ogd-smn_aeg_m.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_m.csv'),
 ('ogd-smn_aeg_t_historical_2000-2009.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_t_historical_2000-2009.csv'),
 ('ogd-smn_aeg_t_historical_2010-2019.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_t_historical_2010-2019.csv'),
 ('ogd-smn_aeg_t_historical_2020-2029.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_t_historical_2020-2029.csv'),
 ('ogd-smn_aeg_t_now.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_t_now.csv'),
 ('ogd-smn_aeg_t_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_t_recent.csv'),
 ('ogd-smn_aeg_y.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_y.csv'),
 ('ogd-smn_aig_d_historical.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_d_historical.csv'),
 ('ogd-smn_aig_d_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_d_recent.csv'),
 ('ogd-smn_aig_h_historical_1980-1989.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_h_historical_1980-1989.csv'),
 ('ogd-smn_aig_h_historical_1990-1999.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_h_historical_1990-1999.csv'),
 ('ogd-smn_aig_h_historical_2000-2009.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_h_historical_2000-2009.csv'),
 ('ogd-smn_aig_h_historical_2010-2019.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_h_historical_2010-2019.csv'),
 ('ogd-smn_aig_h_historical_2020-2029.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_h_historical_2020-2029.csv'),
 ('ogd-smn_aig_h_now.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_h_now.csv'),
 ('ogd-smn_aig_h_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_h_recent.csv'),
 ('ogd-smn_aig_m.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_m.csv'),
 ('ogd-smn_aig_t_historical_2000-2009.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_t_historical_2000-2009.csv'),
 ('ogd-smn_aig_t_historical_2010-2019.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_t_historical_2010-2019.csv'),
 ('ogd-smn_aig_t_historical_2020-2029.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_t_historical_2020-2029.csv'),
 ('ogd-smn_aig_t_now.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_t_now.csv'),
 ('ogd-smn_aig_t_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_t_recent.csv'),
 ('ogd-smn_aig_y.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_y.csv'),
 ('ogd-smn_alt_d_historical.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_d_historical.csv'),
 ('ogd-smn_alt_d_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_d_recent.csv'),
 ('ogd-smn_alt_h_historical_1980-1989.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_h_historical_1980-1989.csv'),
 ('ogd-smn_alt_h_historical_1990-1999.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_h_historical_1990-1999.csv'),
 ('ogd-smn_alt_h_historical_2000-2009.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_h_historical_2000-2009.csv'),
 ('ogd-smn_alt_h_historical_2010-2019.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_h_historical_2010-2019.csv'),
 ('ogd-smn_alt_h_historical_2020-2029.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_h_historical_2020-2029.csv'),
 ('ogd-smn_alt_h_now.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_h_now.csv'),
 ('ogd-smn_alt_h_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_h_recent.csv'),
 ('ogd-smn_alt_m.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_m.csv'),
 ('ogd-smn_alt_t_historical_2000-2009.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_t_historical_2000-2009.csv'),
 ('ogd-smn_alt_t_historical_2010-2019.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_t_historical_2010-2019.csv'),
 ('ogd-smn_alt_t_historical_2020-2029.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_t_historical_2020-2029.csv'),
 ('ogd-smn_alt_t_now.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_t_now.csv'),
 ('ogd-smn_alt_t_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_t_recent.csv'),
 ('ogd-smn_alt_y.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_y.csv'),
 ('ogd-smn_and_d_historical.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_d_historical.csv'),
 ('ogd-smn_and_d_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_d_recent.csv'),
 ('ogd-smn_and_h_historical_2000-2009.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_h_historical_2000-2009.csv'),
 ('ogd-smn_and_h_historical_2010-2019.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_h_historical_2010-2019.csv'),
 ('ogd-smn_and_h_historical_2020-2029.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_h_historical_2020-2029.csv'),
 ('ogd-smn_and_h_now.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_h_now.csv'),
 ('ogd-smn_and_h_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_h_recent.csv'),
 ('ogd-smn_and_m.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_m.csv'),
 ('ogd-smn_and_t_historical_2000-2009.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_t_historical_2000-2009.csv'),
 ('ogd-smn_and_t_historical_2010-2019.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_t_historical_2010-2019.csv'),
 ('ogd-smn_and_t_historical_2020-2029.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_t_historical_2020-2029.csv'),
 ('ogd-smn_and_t_now.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_t_now.csv'),
 ('ogd-smn_and_t_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_t_recent.csv'),
 ('ogd-smn_and_y.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_y.csv'),
 ('ogd-smn_ant_d_historical.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_d_historical.csv'),
 ('ogd-smn_ant_d_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_d_recent.csv'),
 ('ogd-smn_ant_h_historical_2010-2019.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_h_historical_2010-2019.csv'),
 ('ogd-smn_ant_h_historical_2020-2029.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_h_historical_2020-2029.csv'),
 ('ogd-smn_ant_h_now.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_h_now.csv'),
 ('ogd-smn_ant_h_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_h_recent.csv'),
 ('ogd-smn_ant_m.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_m.csv'),
 ('ogd-smn_ant_t_historical_2000-2009.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_t_historical_2000-2009.csv'),
 ('ogd-smn_ant_t_historical_2010-2019.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_t_historical_2010-2019.csv'),
 ('ogd-smn_ant_t_historical_2020-2029.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_t_historical_2020-2029.csv'),
 ('ogd-smn_ant_t_now.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_t_now.csv'),
 ('ogd-smn_ant_t_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_t_recent.csv'),
 ('ogd-smn_ant_y.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_y.csv'),
 ('ogd-smn_arh_d_historical.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_d_historical.csv'),
 ('ogd-smn_arh_d_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_d_recent.csv'),
 ('ogd-smn_arh_h_historical_1990-1999.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_h_historical_1990-1999.csv'),
 ('ogd-smn_arh_h_historical_2000-2009.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_h_historical_2000-2009.csv'),
 ('ogd-smn_arh_h_historical_2010-2019.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_h_historical_2010-2019.csv'),
 ('ogd-smn_arh_h_historical_2020-2029.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_h_historical_2020-2029.csv'),
 ('ogd-smn_arh_h_now.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_h_now.csv'),
 ('ogd-smn_arh_h_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_h_recent.csv'),
 ('ogd-smn_arh_m.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_m.csv'),
 ('ogd-smn_arh_t_historical_2000-2009.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_t_historical_2000-2009.csv'),
 ('ogd-smn_arh_t_historical_2010-2019.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_t_historical_2010-2019.csv'),
 ('ogd-smn_arh_t_historical_2020-2029.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_t_historical_2020-2029.csv'),
 ('ogd-smn_arh_t_now.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_t_now.csv'),
 ('ogd-smn_arh_t_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_t_recent.csv'),
 ('ogd-smn_arh_y.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_y.csv'),
 ('ogd-smn_aro_d_historical.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_d_historical.csv'),
 ('ogd-smn_aro_d_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_d_recent.csv'),
 ('ogd-smn_aro_h_historical_2000-2009.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_h_historical_2000-2009.csv'),
 ('ogd-smn_aro_h_historical_2010-2019.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_h_historical_2010-2019.csv'),
 ('ogd-smn_aro_h_historical_2020-2029.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_h_historical_2020-2029.csv'),
 ('ogd-smn_aro_h_now.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_h_now.csv'),
 ('ogd-smn_aro_h_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_h_recent.csv'),
 ('ogd-smn_aro_m.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_m.csv'),
 ('ogd-smn_aro_t_historical_2000-2009.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_t_historical_2000-2009.csv'),
 ('ogd-smn_aro_t_historical_2010-2019.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_t_historical_2010-2019.csv'),
 ('ogd-smn_aro_t_historical_2020-2029.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_t_historical_2020-2029.csv'),
 ('ogd-smn_aro_t_now.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_t_now.csv'),
 ('ogd-smn_aro_t_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_t_recent.csv'),
 ('ogd-smn_aro_y.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_y.csv'),
 ('ogd-smn_att_d_historical.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_d_historical.csv'),
 ('ogd-smn_att_d_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_d_recent.csv'),
 ('ogd-smn_att_h_historical_1990-1999.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_h_historical_1990-1999.csv'),
 ('ogd-smn_att_h_historical_2000-2009.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_h_historical_2000-2009.csv'),
 ('ogd-smn_att_h_historical_2010-2019.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_h_historical_2010-2019.csv'),
 ('ogd-smn_att_h_historical_2020-2029.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_h_historical_2020-2029.csv'),
 ('ogd-smn_att_h_now.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_h_now.csv'),
 ('ogd-smn_att_h_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_h_recent.csv'),
 ('ogd-smn_att_m.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_m.csv'),
 ('ogd-smn_att_t_historical_2000-2009.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_t_historical_2000-2009.csv'),
 ('ogd-smn_att_t_historical_2010-2019.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_t_historical_2010-2019.csv'),
 ('ogd-smn_att_t_historical_2020-2029.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_t_historical_2020-2029.csv'),
 ('ogd-smn_att_t_now.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_t_now.csv'),
 ('ogd-smn_att_t_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_t_recent.csv'),
 ('ogd-smn_att_y.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_y.csv'),
 ('ogd-smn_ban_d_historical.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_d_historical.csv'),
 ('ogd-smn_ban_d_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_d_recent.csv'),
 ('ogd-smn_ban_h_historical_2010-2019.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_h_historical_2010-2019.csv'),
 ('ogd-smn_ban_h_historical_2020-2029.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_h_historical_2020-2029.csv'),
 ('ogd-smn_ban_h_now.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_h_now.csv'),
 ('ogd-smn_ban_h_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_h_recent.csv'),
 ('ogd-smn_ban_m.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_m.csv'),
 ('ogd-smn_ban_t_historical_2010-2019.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_t_historical_2010-2019.csv'),
 ('ogd-smn_ban_t_historical_2020-2029.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_t_historical_2020-2029.csv'),
 ('ogd-smn_ban_t_now.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_t_now.csv'),
 ('ogd-smn_ban_t_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_t_recent.csv'),
 ('ogd-smn_ban_y.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_y.csv'),
 ('ogd-smn_bas_d_historical.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_d_historical.csv'),
 ('ogd-smn_bas_d_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_d_recent.csv'),
 ('ogd-smn_bas_h_historical_1980-1989.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_h_historical_1980-1989.csv'),
 ('ogd-smn_bas_h_historical_1990-1999.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_h_historical_1990-1999.csv'),
 ('ogd-smn_bas_h_historical_2000-2009.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_h_historical_2000-2009.csv'),
 ('ogd-smn_bas_h_historical_2010-2019.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_h_historical_2010-2019.csv'),
 ('ogd-smn_bas_h_historical_2020-2029.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_h_historical_2020-2029.csv'),
 ('ogd-smn_bas_h_now.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_h_now.csv'),
 ('ogd-smn_bas_h_recent.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_h_recent.csv'),
 ('ogd-smn_bas_m.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_m.csv'),
 ('ogd-smn_bas_t_historical_2000-2009.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_t_historical_2000-2009.csv'),
 ('ogd-smn_bas_t_historical_2010-2019.csv',
  'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_t_historical_2010-2019.csv'),
 ('ogd-smn_bas_t_historical_2020-2029.csv',

In [42]:
assets = [item['assets'] for item in data['features']]
datasets_urls = [
    metadata['href'] 
    for asset in assets
    for metadata in asset.values()
]
datasets_urls

['https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_d_historical.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_d_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_h_historical_1980-1989.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_h_historical_1990-1999.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_h_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_h_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_h_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_h_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_h_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_m.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_t_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_t_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_t_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_t_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_t_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_y.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_d_historical.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_d_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_h_historical_1990-1999.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_h_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_h_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_h_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_h_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_h_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_m.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_t_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_t_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_t_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_t_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_t_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aeg/ogd-smn_aeg_y.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_d_historical.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_d_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_h_historical_1980-1989.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_h_historical_1990-1999.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_h_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_h_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_h_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_h_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_h_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_m.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_t_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_t_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_t_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_t_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_t_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aig/ogd-smn_aig_y.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_d_historical.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_d_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_h_historical_1980-1989.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_h_historical_1990-1999.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_h_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_h_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_h_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_h_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_h_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_m.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_t_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_t_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_t_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_t_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_t_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/alt/ogd-smn_alt_y.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_d_historical.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_d_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_h_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_h_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_h_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_h_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_h_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_m.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_t_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_t_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_t_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_t_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_t_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/and/ogd-smn_and_y.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_d_historical.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_d_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_h_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_h_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_h_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_h_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_m.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_t_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_t_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_t_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_t_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_t_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ant/ogd-smn_ant_y.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_d_historical.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_d_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_h_historical_1990-1999.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_h_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_h_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_h_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_h_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_h_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_m.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_t_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_t_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_t_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_t_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_t_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/arh/ogd-smn_arh_y.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_d_historical.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_d_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_h_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_h_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_h_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_h_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_h_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_m.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_t_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_t_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_t_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_t_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_t_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/aro/ogd-smn_aro_y.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_d_historical.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_d_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_h_historical_1990-1999.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_h_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_h_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_h_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_h_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_h_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_m.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_t_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_t_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_t_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_t_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_t_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/att/ogd-smn_att_y.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_d_historical.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_d_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_h_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_h_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_h_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_h_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_m.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_t_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_t_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_t_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_t_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ban/ogd-smn_ban_y.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_d_historical.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_d_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_h_historical_1980-1989.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_h_historical_1990-1999.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_h_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_h_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_h_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_h_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_h_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_m.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_t_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_t_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_t_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_t_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_t_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bas/ogd-smn_bas_y.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/beh/ogd-smn_beh_d_historical.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/beh/ogd-smn_beh_d_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/beh/ogd-smn_beh_h_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/beh/ogd-smn_beh_h_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/beh/ogd-smn_beh_h_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/beh/ogd-smn_beh_h_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/beh/ogd-smn_beh_m.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/beh/ogd-smn_beh_t_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/beh/ogd-smn_beh_t_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/beh/ogd-smn_beh_t_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/beh/ogd-smn_beh_t_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/beh/ogd-smn_beh_t_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/beh/ogd-smn_beh_y.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ber/ogd-smn_ber_d_historical.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ber/ogd-smn_ber_d_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ber/ogd-smn_ber_h_historical_1980-1989.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ber/ogd-smn_ber_h_historical_1990-1999.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ber/ogd-smn_ber_h_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ber/ogd-smn_ber_h_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ber/ogd-smn_ber_h_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ber/ogd-smn_ber_h_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ber/ogd-smn_ber_h_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ber/ogd-smn_ber_m.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ber/ogd-smn_ber_t_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ber/ogd-smn_ber_t_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ber/ogd-smn_ber_t_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ber/ogd-smn_ber_t_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ber/ogd-smn_ber_t_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/ber/ogd-smn_ber_y.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bez/ogd-smn_bez_d_historical.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bez/ogd-smn_bez_d_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bez/ogd-smn_bez_h_historical_1980-1989.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bez/ogd-smn_bez_h_historical_1990-1999.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bez/ogd-smn_bez_h_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bez/ogd-smn_bez_h_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bez/ogd-smn_bez_h_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bez/ogd-smn_bez_h_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bez/ogd-smn_bez_h_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bez/ogd-smn_bez_m.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bez/ogd-smn_bez_t_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bez/ogd-smn_bez_t_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bez/ogd-smn_bez_t_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bez/ogd-smn_bez_t_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bez/ogd-smn_bez_t_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bez/ogd-smn_bez_y.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bia/ogd-smn_bia_d_historical.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bia/ogd-smn_bia_d_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bia/ogd-smn_bia_h_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bia/ogd-smn_bia_h_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bia/ogd-smn_bia_h_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bia/ogd-smn_bia_h_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bia/ogd-smn_bia_m.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bia/ogd-smn_bia_t_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bia/ogd-smn_bia_t_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bia/ogd-smn_bia_t_now.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bia/ogd-smn_bia_t_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bia/ogd-smn_bia_y.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bie/ogd-smn_bie_d_historical.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bie/ogd-smn_bie_d_recent.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bie/ogd-smn_bie_h_historical_1990-1999.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bie/ogd-smn_bie_h_historical_2000-2009.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bie/ogd-smn_bie_h_historical_2010-2019.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bie/ogd-smn_bie_h_historical_2020-2029.csv',
 'https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/bie/ogd-smn_bie_h_now.csv',

In [15]:
import json
print(json.dumps(df.loc[0, "assets"], indent=2))

{
  "ogd-smn_abo_d_historical.csv": {
    "type": "text/csv",
    "href": "https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_d_historical.csv",
    "created": "2025-04-30T14:41:10.057044Z",
    "updated": "2026-02-18T19:51:01.708966Z",
    "file:checksum": "1220d52abfa2576e904bf993b974fca929a3ead3a72f3bdabf97eff4ea7b30c6bacf"
  },
  "ogd-smn_abo_d_recent.csv": {
    "type": "text/csv",
    "href": "https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_d_recent.csv",
    "created": "2025-04-04T10:18:03.648692Z",
    "updated": "2026-07-01T01:57:35.585815Z",
    "file:checksum": "122046b4e849753f311cad871a97deab4a39bc50567516e2b57d5b8d8357097e30e9"
  },
  "ogd-smn_abo_h_historical_1980-1989.csv": {
    "type": "text/csv",
    "href": "https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_h_historical_1980-1989.csv",
    "created": "2025-04-30T14:39:11.737854Z",
    "updated": "2026-02-18T19:51:01.502005Z",
    "file:checksum": "1220d018dc61afa1779e78f8f05e5abf59112993a2fee63cffd8710774ce3d0e4ef1"
  },
  "ogd-smn_abo_h_historical_1990-1999.csv": {
    "type": "text/csv",
    "href": "https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_h_historical_1990-1999.csv",
    "created": "2025-04-30T14:41:10.581902Z",
    "updated": "2026-02-18T19:51:37.598497Z",
    "file:checksum": "122015e1b15681e34126bf160307095a66609316ace40cee7c34f29664dfba2e2668"
  },
  "ogd-smn_abo_h_historical_2000-2009.csv": {
    "type": "text/csv",
    "href": "https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_h_historical_2000-2009.csv",
    "created": "2025-04-30T14:41:10.149697Z",
    "updated": "2026-02-18T19:51:37.539825Z",
    "file:checksum": "1220a7e351d4033d54a8e7a243c9c245ec0470a4eeb37181c54729b38a68782bc1c9"
  },
  "ogd-smn_abo_h_historical_2010-2019.csv": {
    "type": "text/csv",
    "href": "https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_h_historical_2010-2019.csv",
    "created": "2025-04-30T14:43:09.118612Z",
    "updated": "2026-02-18T19:51:38.369481Z",
    "file:checksum": "122090dc0ff1b6bbfdbc73c1101040a6b4bbaa1ebcf7368c694b70d8ecc2fe3a93e8"
  },
  "ogd-smn_abo_h_historical_2020-2029.csv": {
    "type": "text/csv",
    "href": "https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_h_historical_2020-2029.csv",
    "created": "2025-04-30T14:41:10.271567Z",
    "updated": "2026-02-18T19:51:37.477238Z",
    "file:checksum": "1220a89d568c8a810708a6f9e8db1e30316737a3af79c834d42ce60aed98c50bbc8a"
  },
  "ogd-smn_abo_h_now.csv": {
    "type": "text/csv",
    "href": "https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_h_now.csv",
    "created": "2025-04-04T10:04:17.451432Z",
    "updated": "2026-07-01T08:38:02.807287Z",
    "file:checksum": "1220dce2c736f666c6a1af07da91d2b1a0b33977d4b4e3ef05ed8d51a3f5115a2c66"
  },
  "ogd-smn_abo_h_recent.csv": {
    "type": "text/csv",
    "href": "https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_h_recent.csv",
    "created": "2025-04-04T10:23:20.455885Z",
    "updated": "2026-07-01T01:57:35.938245Z",
    "file:checksum": "1220e354d0cab3817b4fb4dfcb6d45f715aa35b9ff2ed1fffd91946db5ba32197d30"
  },
  "ogd-smn_abo_m.csv": {
    "type": "text/csv",
    "href": "https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_m.csv",
    "created": "2025-04-17T09:37:34.086004Z",
    "updated": "2026-06-25T04:29:04.665959Z",
    "file:checksum": "12206425bc9a7ba26278f76f915308c5dbc7a5177244faa36e1f720a1aa1a287a6d3"
  },
  "ogd-smn_abo_t_historical_2000-2009.csv": {
    "type": "text/csv",
    "href": "https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_t_historical_2000-2009.csv",
    "created": "2025-04-30T14:43:09.347088Z",
    "updated": "2026-02-18T19:51:49.450662Z",
    "file:checksum": "1220ef25f6b2d266349b5dc928b02b9b9269a22c8375a206a97ad68306034960d61d"
  },
  "ogd-smn_abo_t_historical_2010-2019.csv": {
    "type": "text/csv",
    "href": "https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_t_historical_2010-2019.csv",
    "created": "2025-04-30T14:45:17.057489Z",
    "updated": "2026-02-18T19:53:45.454437Z",
    "file:checksum": "12200f8f68d76708838f727b00763a61b23d7596e25b367896083cbae82cbd9bbda2"
  },
  "ogd-smn_abo_t_historical_2020-2029.csv": {
    "type": "text/csv",
    "href": "https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_t_historical_2020-2029.csv",
    "created": "2025-04-30T14:45:07.993036Z",
    "updated": "2026-02-18T19:51:49.519933Z",
    "file:checksum": "1220685fee6f426ae6ef07f03146cf69eb159c113210e746ce45fbd27ceb992d56f6"
  },
  "ogd-smn_abo_t_now.csv": {
    "type": "text/csv",
    "href": "https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_t_now.csv",
    "created": "2025-04-04T10:04:22.221007Z",
    "updated": "2026-07-01T07:54:53.522583Z",
    "file:checksum": "122043c4f26f9e974e94182b8a35bb7b9d96236ae9b8d1504fccd90c4376ebde54cf"
  },
  "ogd-smn_abo_t_recent.csv": {
    "type": "text/csv",
    "href": "https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_t_recent.csv",
    "created": "2025-04-04T10:22:53.659234Z",
    "updated": "2026-07-01T01:57:36.759701Z",
    "file:checksum": "1220f2a78239bd600519521f291f77ebad01eb9832e373bb29b07dc9f250362dfd49"
  },
  "ogd-smn_abo_y.csv": {
    "type": "text/csv",
    "href": "https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_y.csv",
    "created": "2025-04-17T09:37:33.360678Z",
    "updated": "2026-06-25T04:29:04.801582Z",
    "file:checksum": "1220bc534fea03712d0b34275effb3ad48a3afadeccab9ede267caee9f0a6b18ce23"
  }
}

In [26]:
meteo_data_csv = pd.read_csv("https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/abo/ogd-smn_abo_d_historical.csv", sep=";")
df_meteo = pd.DataFrame(meteo_data_csv)
df_meteo

,station_abbr,reference_timestamp,tre200d0,tre200dx,tre200dn,tre005d0,tre005dx,tre005dn,ure200d0,pva200d0,...,sremaxdv,erefaod0,xcd000d0,dkl010d0,xno000d0,xno012d0,rreetsd0,tso005d0,tso010d0,tso020d0
0,ABO,01.01.1901 00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ABO,02.01.1901 00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ABO,03.01.1901 00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ABO,04.01.1901 00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ABO,05.01.1901 00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45560,ABO,27.12.2025 00:00,3.2,7.9,-1.0,0.1,10.0,-4.2,39.6,3.0,...,100.0,0.5,0.0,243.0,16.8,8.8,-0.6,NaN,NaN,NaN
45561,ABO,28.12.2025 00:00,2.5,6.9,-0.6,-0.7,9.4,-4.8,39.2,2.9,...,100.0,0.3,0.0,207.0,17.5,9.5,-0.6,NaN,NaN,NaN
45562,ABO,29.12.2025 00:00,3.0,8.8,-0.8,-0.6,9.7,-5.3,37.1,2.8,...,100.0,0.3,0.0,180.0,17.0,9.0,-0.7,NaN,NaN,NaN
45563,ABO,30.12.2025 00:00,-5.5,-0.4,-9.6,-6.6,-0.2,-11.8,78.2,3.1,...,32.0,0.3,0.0,104.0,25.5,17.5,-0.1,NaN,NaN,NaN
45564,ABO,31.12.2025 00:00,-6.9,-2.8,-10.1,-8.4,0.2,-12.6,64.4,2.3,...,100.0,0.1,0.0,153.0,26.9,18.9,-0.4,NaN,NaN,NaN

In [27]:
df_meteo.info()

<class 'pandas.DataFrame'>
RangeIndex: 45565 entries, 0 to 45564
Data columns (total 41 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   station_abbr         45565 non-null  str
 1   reference_timestamp  45565 non-null  str
 2   tre200d0             24472 non-null  float64
 3   tre200dx             21734 non-null  float64
 4   tre200dn             21734 non-null  float64
 5   tre005d0             15359 non-null  float64
 6   tre005dx             15361 non-null  float64
 7   tre005dn             15360 non-null  float64
 8   ure200d0             24471 non-null  float64
 9   pva200d0             23414 non-null  float64
 10  prestad0             19845 non-null  float64
 11  pp0qffd0             0 non-null      float64
 12  ppz850d0             15365 non-null  float64
 13  ppz700d0             0 non-null      float64
 14  pp0qnhd0             7574 non-null   float64
 15  fkl010d0             21912 non-null  float64
 16  fkl010d1             15355 non-null  float64
 17  fu3010d0             21912 non-null  float64
 18  fu3010d1             15355 non-null  float64
 19  fkl010d3             5947 non-null   float64
 20  fu3010d3             5947 non-null   float64
 21  wcc006d0             4449 non-null   float64
 22  rre150d0             45565 non-null  float64
 23  rka150d0             15362 non-null  float64
 24  htoautd0             5749 non-null   float64
 25  gre000d0             15378 non-null  float64
 26  oli000d0             0 non-null      float64
 27  olo000d0             0 non-null      float64
 28  osr000d0             0 non-null      float64
 29  ods000d0             5528 non-null   float64
 30  sre000d0             21702 non-null  float64
 31  sremaxdv             21702 non-null  float64
 32  erefaod0             15376 non-null  float64
 33  xcd000d0             15512 non-null  float64
 34  dkl010d0             15353 non-null  float64
 35  xno000d0             15522 non-null  float64
 36  xno012d0             16436 non-null  float64
 37  rreetsd0             15354 non-null  float64
 38  tso005d0             12532 non-null  float64
 39  tso010d0             12533 non-null  float64
 40  tso020d0             12532 non-null  float64
dtypes: float64(39), str(2)
memory usage: 14.3 MB